.github/workflows/regenerate-readme.yml
Based on https://github.com/wp-cli/scaffold-command/pull/296
=> GH Actions: don't run the "update readme" workflow on forks

.github/workflows/regenerate-readme.yml
The GitHub Actions `set-output` command has been deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update workflow to deal with deprecated GHA `set-output`

.github/workflows/code-quality.yml, .github/workflows/regenerate-readme.yml, .github/workflows/testing.yml
Seems to work fine https://github.com/wp-cli/reusable-workflow-test/pull/1/commits/b1dbde60b576665b84e539af4b4ab267a8ece214
From #35
Related #34
=> Switch reusable workflows to `@main` instead of a hash

.github/ISSUE_TEMPLATE/1-BUG_REPORT.md, .github/ISSUE_TEMPLATE/2-FEATURE_REQUEST.md
It's pretty easy to move issues between repos these days, so we don't need to put this on the user.
=> Remove "Are you in the right destination?" HTML comment in templates

.github/workflows/testing.yml
Updates the `.github/workflows/testing.yml` file to run tests daily. The workflow badges on https://wp-cli.org/dashboard/ are varying degrees of out of date.
=> Make it easier to monitor for regressions by running daily

.github/workflows/code-quality.yml, .github/workflows/regenerate-readme.yml, .github/workflows/testing.yml
It's used in some of the workflows, and they break without it
From https://github.com/wp-cli/package-command/pull/164
See https://github.com/wp-cli/wp-cli/issues/5720
=> Pass `GITHUB_TOKEN` to the reusable workflow

.github/workflows/reusable-code-quality.yml, .github/workflows/reusable-regenerate-readme.yml, .github/workflows/reusable-testing.yml
From https://github.com/wp-cli/.github/pull/48
=> Allow `GITHUB_TOKEN` to be passed into the reusable workflow

.github/workflows/code-quality.yml, .github/workflows/regenerate-readme.yml, .github/workflows/testing.yml
Reverts wp-cli/.github#48
See https://github.com/wp-cli/wp-cli/issues/5720
It breaks all of the tests 😔 https://wordpress.slack.com/archives/C02RP4T41/p1673464502434829
=> Revert "Pass `GITHUB_TOKEN` to the reusable workflow"

.github/workflows/reusable-testing.yml
Trunk bumped the PHP version requirement to 7.0+, see https://make.wordpress.org/core/2023/07/05/dropping-support-for-php-5/
Once 6.3 is released we'll also need to remove the latest+5.6 combo
=> Run trunk tests on PHP 7.0+

.github/workflows/reusable-testing.yml
PHP 8.3 is nearing the RC phase. As WP-CLI is used in the build processes of plenty of other WP packages, I believe it would be beneficial to start supporting PHP 8.3 officially sooner rather than later.
This commit adds PHP 8.3 to the build matrix to start running the tests against PHP 8.3.
Note: I'm not sure how to test the workflow as things are, so I hope I've done it correctly. I've also opened a PR in the Behat repo to start running their tests against PHP 8.3 (Behat/Behat#1440) and their build currently passes, so I expect that the tooling used should all work on PHP 8.3.
Having said that, whether PHP 8.3 can be supported without any fixes will need to be evaluated individually for each WP-CLI repo, so for now, I've added a `continue-on-error` for PHP 8.3 to be on the safe side.
=> GHA/reusable-testing: start running the tests against PHP 8.3

.github/workflows/sync-workflows.yml
The sync workflow currently fails because of this
=> Remove deleted repo from sync workflow

.github/workflows/reusable-code-quality.yml
Use the [Action Validator](https://github.com/mpalmer/action-validator) to do some initial smoke testing of the GitHub Actions workflows.
=> Add GHA workflow validation

.github/workflows/reusable-testing.yml, .github/workflows/sync-workflows.yml, matrix.json
This is an alternative approach to #47 and #75 so we can keep the `minimum-php` input and don't have to add new ones. 
How it works:
Two new jobs are added to prepare the test matrix for the actual test jobs.
The full matrix is now in a JSON file. Is then processed by `jq` to filter out entries where the PHP version is below `minimum-php`. The test jobs then use this filtered matrix with `fromJson`
This way we avoid unused containers from being created.
Also excludes `testing.yml` from syncing.
Example:
The final matrix for the unit tests will look something like this for `minimum-php = 7.0`:
```json
{"include":[{"php":"7.0"},{"php":"7.0"},{"php":"7.1"},{"php":"7.1"},{"php":"7.2"},{"php":"7.2"},{"php":"7.3"},{"php":"7.3"},{"php":"7.4"},{"php":"7.4"},{"php":"8.0"},{"php":"8.0"},{"php":"8.1" …
```
=> Dynamically create test matrix

.github/workflows/reusable-testing.yml, .github/workflows/sync-workflows.yml, .github/workflows/testing.yml
Brings the matrix inline into the workflow instead of fetching it remotely from the repository.
Downside: No syntax highlighting
Upside: No need for a curl call; matrix is closer to the workflow, making it easier to grasp
Successfully tested by running this both correctly against this branch as well [over at this repo](https://github.com/wp-cli/checksum-command/pull/118)
---
This is the second attempt at #78
The original description is below:
How it works:
Two new jobs are added to prepare the test matrix for the actual test jobs.
The full matrix is now in a JSON string. Is then processed by `jq` to filter out entries where the PHP version is below `minimum-php`. The test jobs then use this filtered matrix with `fromJson`
This way we avoid unused containers from being created.
Also …
=> Dynamically create test matrix, take 2

.github/workflows/reusable-testing.yml
Right now we generate a complex build matrix for unit & function tests, and within each job check if we actually need to run the tests or not.
Thanks to the new separate job for building the matrix we can simple build an empty matrix if the relevant files do not exist.
For example, in this repo no test jobs should be started because there are no tests. [Or in the checksum command repo](https://github.com/wp-cli/checksum-command/pull/118), no unit tests should be run because there are non.
=> Do not run matrix if required files do not exist

.github/workflows/reusable-testing.yml
Follow-up to #88
Weirdly I did not run into this when testing the workflow in the other repo, but a run here did complain, see https://github.com/wp-cli/.github/actions/runs/6754981094
This fixes it.
=> Prevent warnings/errors for empty matrix

.github/workflows/reusable-code-quality.yml
Fixes: https://github.com/wp-cli/wp-cli-tests/issues/174
Related: https://github.com/wp-cli/wp-cli/issues/5859
=> Update PHPCS workflow to add full report in CI logs

.github/workflows/reusable-testing.yml
Need to merge this to stop any trunk tests from failing, as WP just increased the minimum required PHP version to 7.2.24, see https://core.trac.wordpress.org/changeset/57985
Also adds experimental tests against PHP 8.4 alpha so that we can spot any issues early.
=> Test WordPress trunk on PHP 7.2+

.github/workflows/reusable-testing.yml
* Latest version (6.6) requires minimum PHP 7.2
=> Update matrix to remove WP 6.6 with PHP less than 7.2

.github/workflows/reusable-testing.yml
The default setting for `error_reporting` used by the SetupPHP action is `error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT` and `display_errors` is set to `Off`.
For the purposes of CI, I'd recommend running with `-1` (always include all error levels on all PHP versions) and `display_errors=On` to ensure **all** PHP notices are shown.
This is now fixed by adding the `ini-values` setting to `setup-php`.
=> GH Actions/tests: set error reporting to display all notices

.github/workflows/reusable-code-quality.yml
While rare, there are some deprecations which PHP can show when a file is being linted. By default these are ignored by PHP-Parallel-Lint.
However, there is an option to show them, so let's turn that option on.
To make the option effective, we also need to ensure that PHP is run in a way that all errors will be shown, which is not the case by default, so this also sets some `ini-values` for PHP to a more optimal setting for CI.
Lastly, in the command, let's also make the package directory iteration a little faster by preventing parallel lint from having to iterate through the `.git` directory when there are no PHP files to be found there anyway.
=> GH Actions/linting: show deprecations when linting

.github/workflows/reusable-testing.yml
Setup-PHP has an alias available for "PHP next" named `nightly`.
While this change doesn't remove the annual task of updating the matrix when a new PHP version gets released, it does make this update a little less error prone as updating the `continue-on-error` conditions lower down in the scripts (disconnected from the matrix set up) can easily be forgotten.
There are a few caveats to keep in mind about this change though:
* Manually updating the matrix and the workflow gives (of course) more control over the exact PHP versions being used.
* When using `nightly`, that control is relinquished partially to setup-php and partially to PHP itself as `nightly` will generally always be "PHP next".
This means that `nightly` will effectively become PHP `8.5` at the time when setup-php updates the …
=> GH Actions/testing: minor simplification/maintainability improvement

.github/workflows/reusable-testing.yml
The configuration file specification has undergone changes in PHPUnit 9.3 and 10.0.
Most notably:
* In PHPUnit 9.3, the manner of specifying the code coverage configuration has changed.
* In PHPUnit 10.0, a significant number of attributes of the `<phpunit>` element were removed or renamed.
When running PHPUnit 10 with  a PHPUnit 9 style configuration file, PHPUnit 10 can show a warning:
```
There was 1 PHPUnit test runner deprecation:
1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
```
The `--migrate-configuration` command can upgrade a configuration for the changes in the format made in PHPUnit 9.3 and 10.0/10.1, but some of the changes in the configuration format in PHPUnit 10 don't have one-on-one …
=> GH Actions/tests: prevent warning about outdated configuration being used

dependabot.yml
Currently, Dependabot only looks for Composer dependency updates. However, there are also GitHub Actions workflows included in this repository, which make use of third-party actions.
This PR updates the Dependabot config file to also cover GHA dependencies. This is actually in line with how some WP-CLI package repositories have the `dependabot.yml` file set up, so I thought it made sense to add it to this repository too.
=> Let Dependabot update GitHub Actions dependencies

.github/workflows/reusable-testing.yml
This is a follow-up to #105 which set error reporting to display all notices.
While this change already helped catch some bugs, it also currently prevents us from running Behat tests on PHP 8.4 due to the deprecations thrown in Behat.
This is meant to be a temporary change until a new Behat version without the deprecations is available, allowing us to at least run the tests again.
=> Disable error reporting for Behat tests on 8.4

.github/workflows/reusable-testing.yml
This reverts commit 2c169bf7862a55c2fc021a7fe9c8b12291edefc4 and addc0927be6e45fe29273ab66ef40e38f2532968.
[Behat v3.15.0](https://github.com/Behat/Behat/releases/tag/v3.15.0) was just released with improved PHP 8.4 support, so there shouldn't be any more deprecation warnings when running Behat tests on PHP 8.4
=> Revert "Disable error reporting for Behat tests on 8.4"

.github/workflows/reusable-testing.yml
PHP 8.4 needs to be explicitly required now. PHP "nightly" is now PHP 8.5.
Ref: https://www.php.net/releases/8.4/en.php
=> GH Actions: PHP 8.4 has been released

.github/workflows/reusable-testing.yml
This reverts #114 again for PHP 8.4 and nightly, because we can't actually use Behat v3.15.0 just yet without bumping our minimum PHP version requirement. See https://github.com/wp-cli/wp-cli-tests/pull/228
=> Fix Behat error reporting once again

.github/workflows/reusable-testing.yml
See https://github.com/wp-cli/wp-cli/issues/6035
Updates the matrix and test steps to collect code coverage for Behat and PHPUnit. Upload is then going to Codecov.
Note: Codecov upload requires a token to be set. So maybe check for existence of a config file first?
=> Code coverage support

.github/workflows/reusable-testing.yml
`RUNNER_DEBUG` is set only if [debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) is enabled, and always has the value of 1. It can be useful as an indicator to enable additional debugging or verbose logging in your own job steps.
=> Use pretty Behat output if debug logging is on

.github/workflows/reusable-code-quality.yml
Noticed in https://github.com/wp-cli/wp-cli-dev/pull/62 that the `parallel-script` suddenly started [throwing errors for some of the checked out repos](https://github.com/wp-cli/wp-cli-dev/actions/runs/14882910442/job/41795030519?pr=62) within `wp-cli-dev`. We should be able to exclude them all using this additional input.
=> Add input to exclude additional folders from `parallel-lint`
