wp-cli/.github

.github/ISSUE_TEMPLATE/2-FEATURE_REQUEST.md

Fixes https://github.com/wp-cli/wp-cli/issues/5255

Clarify `wp-cli/ideas` purpose

---

.github/workflows/phpcs.yml

Adds a GitHub Actions workflow that checks for the existence of a PHPCS configuration file, and if that's the case, it runs PHPCS and adds detected issues as PR annotations on a PR.

Add initial PHPCS workflow

---

.github/workflows/code-quality.yml
.github/workflows/regenerate-readme.yml
.github/workflows/testing.yml

Based on https://github.com/wp-cli/scaffold-command/pull/293

GH Actions: simplify Composer caching

---

.github/workflows/regenerate-readme.yml

Adapt `.github/workflows/regenerate-readme.yml` to variable default branch across repos.

Adapt to variable default branch 

---

.github/workflows/sync-workflows.yml

See https://github.com/wp-cli/php-cli-tools/issues/150

Sync workflows to `wp-cli/php-cli-tools`

---

.github/workflows/code-quality.yml
.github/workflows/regenerate-readme.yml
.github/workflows/testing.yml

From https://github.com/wp-cli/.github/pull/34

Runner workflows need to specify a version

---

.github/workflows/reusable-code-quality.yml
.github/workflows/reusable-regenerate-readme.yml
.github/workflows/reusable-testing.yml

Based on https://github.com/WordPress/Requests/pull/775

GHA: bust the cache semi-regularly

---

.github/workflows/reusable-code-quality.yml
.github/workflows/reusable-regenerate-readme.yml
.github/workflows/reusable-testing.yml

Ref https://github.com/WordPress/Requests/pull/780

Update custom-cache-suffix 

---

.github/workflows/reusable-testing.yml

Add PHP 8.2 to testing workflow

---

.github/workflows/testing.yml

See https://github.com/wp-cli/.github/pull/44#issuecomment-1371911159

Run daily testing at a random time

---

.github/workflows/reusable-code-quality.yml
.github/workflows/reusable-regenerate-readme.yml
.github/workflows/reusable-testing.yml

Revert "Allow `GITHUB_TOKEN` to be passed into the reusable workflow"

---

.github/workflows/reusable-testing.yml

Fixes https://github.com/wp-cli/wp-cli-bundle/issues/471

Use Composer 2.2 LTS for PHP < 7.2

---

.github/workflows/reusable-testing.yml

Update MySQL options in testing workflow to  try to resolve intermittent failures.
See https://github.com/wp-cli/wp-cli-tests/issues/160

Update MySQL options in testing workflow

---

.github/workflows/reusable-testing.yml

See https://github.com/wp-cli/wp-cli-tests/issues/160

Try a 30s interval instead of 15s

---

.editorconfig
.github/workflows/sync-workflows.yml

Fixes https://github.com/wp-cli/.github/issues/59

Introduce an `.editorconfig` to be applied across all repos

---

.github/workflows/reusable-testing.yml

Follow-up to https://github.com/wp-cli/wp-cli-tests/pull/181
Runs tests against SQLite but allows them to fail.
Here be dragons 🐉

Run tests against SQLite

---

.github/workflows/reusable-testing.yml

From https://github.com/wp-cli/.github/pull/78

Try referencing the full path to the reusable GitHub action

---

.github/workflows/reusable-testing.yml

To avoid generatin a job when matrix if empty.

Move `needs` up in `reusable-testing.yml`

---

.github/workflows/reusable-testing.yml

Do not mark PHP 8.3 tests as allowed to fail

---

.github/workflows/reusable-testing.yml

See https://github.com/wp-cli/wp-cli-tests/pull/245

Provide `--xdebug` flag to Behat

---

.github/workflows/reusable-testing.yml

fixes https://github.com/wp-cli/.github/issues/123

Add MariaDB to a testing matrix

---

.github/workflows/reusable-regenerate-readme.yml
.github/workflows/reusable-testing.yml

See https://github.com/wp-cli/wp-cli/issues/6026

Bump minimum PHP & WP versions

---

.github/workflows/reusable-code-quality.yml

See https://github.com/wp-cli/wp-cli-tests/issues/203

Add PHPStan workflow job
